### PR TITLE
texi2txt: Use ChangeLog date instead of build date

### PR DESCRIPTION
**Pull request by jubalh**
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good.

This date call works with GNU date and BSD date.

Without this patch, /usr/share/doc/packages/WindowMaker/README.i18n will differ in the line
Published by The Window Maker team on ...

An alternative solution could use the $SOURCE_DATE_EPOCH variable defined in https://reproducible-builds.org/specs/source-date-epoch/

### CODE REVIEW

**Comment by jubalh** [comment]
Upstreaming this patch which we use in our openSUSE package.
Author: @bmwiedemann

**Comment by d-torrance** [comment]
Please submit patches to wmaker-dev@googlegroups.com.  Thanks!

**Comment by jubalh** [comment]
AFAIK GitHub has a setting where you disable pull requests for your repo.
It might be good to disable them to not confuse people. Or mention the fact that PRs won't be accepted in the README (did I overlook it?).

I'll see when I get around to sending it via mail.

**Comment by d-torrance** [comment]
> AFAIK GitHub has a setting where you disable pull requests for your repo. It might be good to disable them to not confuse people.

There doesn't appear to be, or we would have done this. See, for example, https://github.com/dear-github/dear-github/issues/84

>  Or mention the fact that PRs won't be accepted in the README (did I overlook it?).

It's in the repository description.

> I'll see when I get around to sending it via mail.

Thanks!

**Comment by jubalh** [comment]
> It's in the repository description.

Indeed I missed that!

**Pull request closed without merging**
